### ISSUE TITLE
Asynchronously send updated currentBid and bid history to frontend

### ISSUE THREAD

**Issue by nhannpl** [Jidanur/Real-time-auction#10]
- Only send the message to frontend when there is a new change. Frontend will not constantly asking ("Do you have anything new?") to avoid latency.

**Comment by nhannpl** [comment]
Example https://turkogluc.com/server-sent-events-with-spring-boot-and-reactjs/


@nhannpl add listener to frontend

**Comment by Jidanur** [comment]
That's the last thing I would do today need some time to make it work
