### ISSUE TITLE
For each api request, make sure to send different responses to frontend for different meaning:

### ISSUE THREAD

**Issue by nhannpl** [Jidanur/Real-time-auction#11]
For example:
+ Login: if a user is verified, send OK; if the message can't load/send, send 404.; if a user cannot be found, send something else
+Signup: if a user is first signed up and verified, send OK, if there is an error, send 404,; if a user already exists, send something else.
+ etc
+

**Comment by nhannpl** [comment]
@nhannpl handle those messages in frontend

**Comment by Jidanur** [comment]
Similar message as image response

**Comment by nhannpl** [comment]
@Jidanur Image is being updated.

**Comment by Jidanur** [comment]
> @Jidanur Image is being updated.

only the response object gonna change

**Comment by Jidanur** [comment]
During signUP(create in backend)-- send 201 if success or send 500 if error adding else 302 if already exists along with Responsemessage

during login-- send 200 if found else if not found send 404 with message
