### ISSUE TITLE
Frontend: Bidding history is updated when new bid is submitted and validated

### ISSUE THREAD

**Issue by nhannpl** [Jidanur/Real-time-auction#16]
Display correctly in the bidding page

**Comment by Jidanur** [comment]
Auction record saves the recent bids as name-bid-timestamp format as string so u gotta use it how u want in the frontend

**Comment by nhannpl** [comment]
@Jidanur. Frontend needs the info about the price of each bid as well

**Comment by Jidanur** [comment]
We don't have a database table for that not possible with our implementation
