### ISSUE TITLE
Load tests

### ISSUE THREAD

**Issue by nhannpl** [Jidanur/Real-time-auction#17]
Create 1000x auctions 
Sending 1000x bid submits to each of 1000x auctions

Measuring time response and latency

**Comment by nhannpl** [comment]
@be careful with extreme big table: update ID type to BigInt

**Comment by Jidanur** [comment]
Not needed for now, for our project I don't think even with load tests we gonna overflow integer. Also bidding is the big part which we don't even store so nothing to worry about
