### ISSUE TITLE
Add more verification logic when creating an auction: AuctionDao

### ISSUE THREAD

**Issue by nhannpl** [Jidanur/Real-time-auction#9]
1) Title, description, and and any fields that do not have a default value  cannot be empty 
2) Startime <endtime
3) Start time cannot be in the past 
4) Make sure to send different messages each case (including 404 for any other case that cannot be handled) so the frontend can display meaningful messages to users

**Comment by Jidanur** [comment]
I'll send same message as image response

**Comment by nhannpl** [comment]
@Jidanur This is for cheking if the request contains proper info about time and other fields. Do not add the auction if any field does not meet requirement.

**Comment by Jidanur** [comment]
done
-if created 201
-if invalid time send 400 with message
-if user does not exists send 400 with message
